# ---------------------------------------------------------------------------
# coding_esenciales.py
# Created on: lun. sept. 05 2011 01:14:33 
#   (generated by ArcGIS/ModelBuilder)
# Usage: coding_esenciales <LE_SoloEsenciales_Sup0> 
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Load required toolboxes...
gp.AddToolbox("C:/Program Files (x86)/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")

# Script arguments...
LE_SoloEsenciales_Sup0 = sys.argv[1]
if LE_SoloEsenciales_Sup0 == '#':
 LE_SoloEsenciales_Sup0 = "LE_SoloEsenciales_Sup0" # provide a default value if unspecified

# Local variables...
ag_code = "LE_SoloEsenciales_Sup0"
al_code = "LE_SoloEsenciales_Sup0"
en_code = "LE_SoloEsenciales_Sup0"
sa_code = "LE_SoloEsenciales_Sup0"
tr_code = "LE_SoloEsenciales_Sup0"
te_code = "LE_SoloEsenciales_Sup0"
de_code = "LE_SoloEsenciales_Sup0"
re_code = "LE_SoloEsenciales_Sup0"
es_code = "LE_SoloEsenciales_Sup0"
sel_AgE = "LE_SoloEsenciales_Sup0"
AgE_coded = "LE_SoloEsenciales_Sup0"
sel_EnE = "LE_SoloEsenciales_Sup0"
EnE_coded = "LE_SoloEsenciales_Sup0"
sel_TrE = "LE_SoloEsenciales_Sup0"
TrE_coded = "LE_SoloEsenciales_Sup0"
sel_DeE = "LE_SoloEsenciales_Sup0"
DeE_coded = "LE_SoloEsenciales_Sup0"
sel_EsE = "LE_SoloEsenciales_Sup0"
EsE_coded = "LE_SoloEsenciales_Sup0"
sel_AlbE = "LE_SoloEsenciales_Sup0"
ReE_coded = "LE_SoloEsenciales_Sup0"
sel_Ali = "LE_SoloEsenciales_Sup0"
AliE_coded = "LE_SoloEsenciales_Sup0"
sel_Tel = "LE_SoloEsenciales_Sup0"
TelE_coded = "LE_SoloEsenciales_Sup0"
sel_Sal = "LE_SoloEsenciales_Sup0"
SalE_coded = "LE_SoloEsenciales_Sup0"
Sortie_avec_champs = "LE_SoloEsenciales_Sup0"
cleared = "LE_SoloEsenciales_Sup0"
Sortie_propre = "LE_SoloEsenciales_Sup0"
Champ_code_types_propre = "LE_SoloEsenciales_Sup0"

# Process: Add ag_code...
gp.AddField_management(LE_SoloEsenciales_Sup0, "ag_code", "TEXT", "", "", "1", "", "NON_NULLABLE", "NON_REQUIRED", "")

# Process: Select AgE...
gp.SelectLayerByAttribute_management(ag_code, "NEW_SELECTION", "\"AGUA_E\"=1")

# Process: Calculate Field...
gp.CalculateField_management(sel_AgE, "ag_code", "\"A\"", "VB", "")

# Process: Add al_code...
gp.AddField_management(LE_SoloEsenciales_Sup0, "al_code", "TEXT", "", "", "1", "", "NON_NULLABLE", "NON_REQUIRED", "")

# Process: Select AliE...
gp.SelectLayerByAttribute_management(al_code, "NEW_SELECTION", "\"ALIMEN_E\" =1")

# Process: Calculate Field (7)...
gp.CalculateField_management(sel_Ali, "al_code", "\"L\"", "VB", "")

# Process: Add de_code...
gp.AddField_management(LE_SoloEsenciales_Sup0, "de_code", "TEXT", "", "", "1", "", "NON_NULLABLE", "NON_REQUIRED", "")

# Process: Select DeE...
gp.SelectLayerByAttribute_management(de_code, "NEW_SELECTION", "\"DECIS_E\" =1")

# Process: Calculate Field (4)...
gp.CalculateField_management(sel_DeE, "de_code", "\"D\"", "VB", "")

# Process: Add en_code...
gp.AddField_management(LE_SoloEsenciales_Sup0, "en_code", "TEXT", "", "", "1", "", "NON_NULLABLE", "NON_REQUIRED", "")

# Process: Select EnE...
gp.SelectLayerByAttribute_management(en_code, "NEW_SELECTION", "\"ENERG_E\" =1")

# Process: Calculate Field (2)...
gp.CalculateField_management(sel_EnE, "en_code", "\"E\"", "VB", "")

# Process: Add es_code...
gp.AddField_management(LE_SoloEsenciales_Sup0, "es_code", "TEXT", "", "", "1", "", "NON_NULLABLE", "NON_REQUIRED", "")

# Process: Select EsE...
gp.SelectLayerByAttribute_management(es_code, "NEW_SELECTION", "\"ESCOMB_E\" =1")

# Process: Calculate Field (5)...
gp.CalculateField_management(sel_EsE, "es_code", "\"B\"", "VB", "")

# Process: Add re_code...
gp.AddField_management(LE_SoloEsenciales_Sup0, "re_code", "TEXT", "", "", "1", "", "NON_NULLABLE", "NON_REQUIRED", "")

# Process: Select AlbE...
gp.SelectLayerByAttribute_management(re_code, "NEW_SELECTION", "\"ALBERG_E\" =1")

# Process: Calculate Field (6)...
gp.CalculateField_management(sel_AlbE, "re_code", "\"R\"", "VB", "")

# Process: Add sa_code...
gp.AddField_management(LE_SoloEsenciales_Sup0, "sa_code", "TEXT", "", "", "1", "", "NON_NULLABLE", "NON_REQUIRED", "")

# Process: Select SalE...
gp.SelectLayerByAttribute_management(sa_code, "NEW_SELECTION", "\"SALUD_E\" =1")

# Process: Calculate Field (9)...
gp.CalculateField_management(sel_Sal, "sa_code", "\"S\"", "VB", "")

# Process: Add te_code...
gp.AddField_management(LE_SoloEsenciales_Sup0, "te_code", "TEXT", "", "", "1", "", "NON_NULLABLE", "NON_REQUIRED", "")

# Process: Select TelE...
gp.SelectLayerByAttribute_management(te_code, "NEW_SELECTION", "\"TELECOM_E\" =1")

# Process: Calculate Field (8)...
gp.CalculateField_management(sel_Tel, "te_code", "\"C\"", "VB", "")

# Process: Add tr_code...
gp.AddField_management(LE_SoloEsenciales_Sup0, "tr_code", "TEXT", "", "", "1", "", "NON_NULLABLE", "NON_REQUIRED", "")

# Process: Select TrE...
gp.SelectLayerByAttribute_management(tr_code, "NEW_SELECTION", "\"TRANSP_E\" =1")

# Process: Calculate Field (3)...
gp.CalculateField_management(sel_TrE, "tr_code", "\"T\"", "VB", "")

# Process: Clear selections...
gp.SelectLayerByAttribute_management(LE_SoloEsenciales_Sup0, "CLEAR_SELECTION", "")

# Process: MAJ_Code_types...
gp.CalculateField_management(cleared, "CODE_types", "[ag_code]+ [al_code]+ [en_code]+ [sa_code]+ [tr_code]+ [te_code]+ [de_code]+[re_code]+[es_code]", "VB", "")

# Process: Suppression espaces...
gp.CalculateField_management(Sortie_avec_champs, "CODE_types", "Replace( [CODE_types] , \" \" , \"\" )", "VB", "")

# Process: Delete Field...
gp.DeleteField_management(Champ_code_types_propre, "ag_code;al_code;de_code;en_code;es_code;re_code;sa_code;te_code;tr_code")

