# ---------------------------------------------------------------------------
# esenciales_corelexclusiva.py
# Created on: Mar Sep 06 2011 02:15:19 p.m.
#   (generated by ArcGIS/ModelBuilder)
# Usage: esenciales_corelexclusiva <LE_grilla_400m_tipo_shp> 
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create()

# Load required toolboxes...
gp.AddToolbox("C:/Archivos de programa/ArcGIS/ArcToolbox/Toolboxes/Data Management Tools.tbx")
gp.AddToolbox("C:/Archivos de programa/ArcGIS/ArcToolbox/Toolboxes/Analysis Tools.tbx")

# Set the Geoprocessing environment...
gp.newPrecision = "SINGLE"
gp.autoCommit = "1000"
gp.XYResolution = ""
gp.XYDomain = ""
gp.scratchWorkspace = "D:\\A ordenar\\Julien\\tratamientos\\mallas"
gp.MTolerance = ""
gp.coincidentPoints = "MEAN"
gp.randomGenerator = "0 ACM599"
gp.outputCoordinateSystem = "PROJCS['WGS_1984_UTM_Zone_18S',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Transverse_Mercator'],PARAMETER['false_easting',500000.0],PARAMETER['false_northing',10000000.0],PARAMETER['central_meridian',-75.0],PARAMETER['scale_factor',0.9996],PARAMETER['latitude_of_origin',0.0],UNIT['Meter',1.0]]"
gp.ZDomain = ""
gp.snapRaster = ""
gp.projectCompare = "NONE"
gp.cartographicCoordinateSystem = ""
gp.configKeyword = ""
gp.outputZFlag = "Same As Input"
gp.qualifiedFieldNames = "true"
gp.referenceScale = ""
gp.extent = "DEFAULT"
gp.XYTolerance = ""
gp.MDomain = ""
gp.spatialGrid1 = "0"
gp.outputZValue = ""
gp.outputMFlag = "Same As Input"
gp.geographicTransformations = ""
gp.spatialGrid2 = "0"
gp.ZResolution = ""
gp.spatialGrid3 = "0"
gp.workspace = "D:\\A ordenar\\Julien\\tratamientos"
gp.MResolution = ""
gp.derivedPrecision = "HIGHEST"
gp.ZTolerance = ""

# Script arguments...
LE_grilla_400m_tipo_shp = sys.argv[1]
if LE_grilla_400m_tipo_shp == '#':
 LE_grilla_400m_tipo_shp = "D:\\Datos\\PACIVUR\\LE_Grilla_400m\\LE_grilla_400m_tipo\\shp\\LE_grilla_400m_tipo.shp" # provide a default value if unspecified

# Local variables...
LE_grilla_400m_tipo = "LE_SoleEsenciales_Egal2"
Agua_con_energia = "LE_SoleEsenciales_Egal2"
LE_aguaE_con_energiaE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_aguaE_con_energiaE.shp"
Agua_con_transporte = "LE_SoleEsenciales_Egal2"
LE_aguaE_con_transporteE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_aguaE_con_transporteE.shp"
Agua_con_decision = "LE_SoleEsenciales_Egal2"
LE_aguaE_con_decisionE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_aguaE_con_decisionE.shp"
Agua_con_escombreras = "LE_SoleEsenciales_Egal2"
LE_aguaE_con_escombrerasE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_aguaE_con_escombrerasE.shp"
Agua_con_alimentos = "LE_SoleEsenciales_Egal2"
LE_aguaE_con_alimentosE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_aguaE_con_alimentosE.shp"
Agua_con_Salud = "LE_SoleEsenciales_Egal2"
LE_aguaE_con_saludE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_aguaE_con_saludE.shp"
Agua_con_telecom = "LE_SoleEsenciales_Egal2"
LE_aguaE_con_telecomE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_aguaE_con_telecomE.shp"
Agua_con_albergue = "LE_SoleEsenciales_Egal2"
LE_aguaE_con_albergueE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_aguaE_con_albergueE.shp"
Alimentos_con_energia = "LE_SoleEsenciales_Egal2"
LE_alimentosE_con_energiaE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_alimentosE_con_energiaE.shp"
Alimentos_con_salud = "LE_SoleEsenciales_Egal2"
LE_alimentosE_con_saludE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_alimentosE_con_saludE.shp"
Alimentos_con_transporte = "LE_SoleEsenciales_Egal2"
LE_alimentosE_con_transporteE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_alimentosE_con_transporteE.shp"
Alimentos_con_telecom = "LE_SoleEsenciales_Egal2"
LE_alimentosE_con_telecomE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_alimentosE_con_telecomE.shp"
Alimentos_con_decision = "LE_SoleEsenciales_Egal2"
LE_alimentosE_con_decisE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_alimentosE_con_decisE.shp"
Alimentos_con_albergue = "LE_SoleEsenciales_Egal2"
LE_alimentosE_con_albergE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_alimentosE_con_albergE.shp"
Alimentos_con_escombreras = "LE_SoleEsenciales_Egal2"
LE_alimentosE_con_escombrerasE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_alimentosE_con_escombrerasE.shp"
LE_alimentosE_con_aguaE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_alimentosE_con_aguaE.shp"
LE_telecomE_con_aguaE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_telecomE_con_aguaE.shp"
LE_decisionE_con_aguaE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_decisionE_con_aguaE.shp"
LE_energiaE_con_aguaE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_energiaE_con_aguaE.shp"
LE_transporteE_con_aguaE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_transporteE_con_aguaE.shp"
LE_escombrerasE_con_aguaE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_escombrerasE_con_aguaE.shp"
LE_saludE_con_aguaE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_saludE_con_aguaE.shp"
LE_albergueE_con_aguaE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_albergueE_con_aguaE.shp"
LE_saludE_con_alimentosE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_saludE_con_alimentosE.shp"
LE_telecomE_con_alimentosE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_telecomE_con_alimentosE.shp"
LE_albergueE_con_alimentosE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_albergueE_con_alimentosE.shp"
LE_escombrerasE_con_alimentosE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_escombrerasE_con_alimentosE.shp"
LE_decisionE_con_alimentosE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_decisionE_con_alimentosE.shp"
LE_transporteE_con_alimentosE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_transporteE_con_alimentosE.shp"
LE_energiaE_con_alimentosE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_energiaE_con_alimentosE.shp"
Energia_con_salud = "LE_SoleEsenciales_Egal2"
LE_energiaE_con_saludE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_energiaE_con_saludE.shp"
Energia_con_transporte = "LE_SoleEsenciales_Egal2"
LE_energiaE_con_transporteE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_energiaE_con_transporteE.shp"
Energia_con_telecom = "LE_SoleEsenciales_Egal2"
LE_energiaE_con_telecomE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_energiaE_con_telecomE.shp"
Energia_con_decision = "LE_SoleEsenciales_Egal2"
LE_energiaE_con_decisionE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_energiaE_con_decisionE.shp"
LE_decisionsE_con_energiaE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_decisionsE_con_energiaE.shp"
LE_telecomE_con_energiaE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_telecomE_con_energiaE.shp"
LE_saludE_con_energiaE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_saludE_con_energiaE.shp"
LE_transporteE_con_energiaE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_transporteE_con_energiaE.shp"
Energia_con_albergue = "LE_SoleEsenciales_Egal2"
LE_energiaE_con_albergueE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_energiaE_con_albergueE.shp"
LE_albergueE_con_energiaE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_albergueE_con_energiaE.shp"
Energia_con_escombreras = "LE_SoleEsenciales_Egal2"
LE_energiaE_con_escombrerasE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_energiaE_con_escombrerasE.shp"
LE_escombrerasE_con_energiaE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_escombrerasE_con_energiaE.shp"
Salud_con_transporte = "LE_SoleEsenciales_Egal2"
LE_saludE_con_transporteE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_saludE_con_transporteE.shp"
LE_transporteE_con_saludE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_transporteE_con_saludE.shp"
Salud_con_telecom = "LE_SoleEsenciales_Egal2"
LE_saludE_con_telecomE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_saludE_con_telecomE.shp"
LE_telecomE_con_saludE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_telecomE_con_saludE.shp"
Salud_con_decision = "LE_SoleEsenciales_Egal2"
LE_saludE_con_decisionE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_saludE_con_decisionE.shp"
LE_decisionE_con_saludE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_decisionE_con_saludE.shp"
Salud_con_albergue = "LE_SoleEsenciales_Egal2"
LE_saludE_con_albergueE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_saludE_con_albergueE.shp"
LE_albergueE_con_saludE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_albergueE_con_saludE.shp"
Salud_con_escombreras = "LE_SoleEsenciales_Egal2"
LE_saludE_con_escombrerasE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_saludE_con_escombrerasE.shp"
LE_escombrerasE_con_saludE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_escombrerasE_con_saludE.shp"
Transporte_con_telecom = "LE_SoleEsenciales_Egal2"
LE_transporteE_con_telecomE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_transporteE_con_telecomE.shp"
LE_telecomE_con_transporteE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_telecomE_con_transporteE.shp"
Transporte_con_decision = "LE_SoleEsenciales_Egal2"
LE_transporteE_con_decisionE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_transporteE_con_decisionE.shp"
LE_decisionE_con_transporteE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_decisionE_con_transporteE.shp"
Transporte_con_albergue = "LE_SoleEsenciales_Egal2"
LE_transporteE_con_albergueE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_transporteE_con_albergueE.shp"
LE_albergueE_con_transporteE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_albergueE_con_transporteE.shp"
Transporte_con_escombreras = "LE_SoleEsenciales_Egal2"
LE_transporteE_con_escombrerasE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_transporteE_con_escombrerasE.shp"
LE_escombrerasE_con_transporteE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_escombrerasE_con_transporteE.shp"
Telecom_con_decision = "LE_SoleEsenciales_Egal2"
LE_telecomE_con_decisionE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_telecomE_con_decisionE.shp"
LE_decisionE_con_telecomE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_decisionE_con_telecomE.shp"
Telecom_con_albergue = "LE_SoleEsenciales_Egal2"
LE_telecomE_con_albergueE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_telecomE_con_albergueE.shp"
LE_albergueE_con_telecomE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_albergueE_con_telecomE.shp"
Telecom_con_escombreras = "LE_SoleEsenciales_Egal2"
LE_telecomE_con_escombrerasE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_telecomE_con_escombrerasE.shp"
LE_escombrerasE_con_telecomE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_escombrerasE_con_telecomE.shp"
Decision_con_albergue = "LE_SoleEsenciales_Egal2"
LE_decisionE_con_albergueE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_decisionE_con_albergueE.shp"
LE_albergueE_con_decisionE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_albergueE_con_decisionE.shp"
Decision_con_escombreras = "LE_SoleEsenciales_Egal2"
LE_decisionE_con_escombrerasE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_decisionE_con_escombrerasE.shp"
LE_escombrerasE_con_decisionE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_escombrerasE_con_decisionE.shp"
Albergue_con_escombreras = "LE_SoleEsenciales_Egal2"
LE_albergueE_con_escombrerasE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_albergueE_con_escombrerasE.shp"
LE_escombrerasE_con_albergueE_shp = "D:\\A ordenar\\Julien\\tratamientos\\mallas\\LE_escombrerasE_con_albergueE.shp"
Row_Count = "31"
Row_Count__3_ = "31"
Row_Count__2_ = "31"
Row_Count__4_ = "31"
Row_Count__5_ = "31"
Row_Count__6_ = "31"
Row_Count__7_ = "31"
Row_Count__8_ = "31"
Row_Count__9_ = "31"
Row_Count__10_ = "31"
Row_Count__11_ = "31"
Row_Count__12_ = "31"
Row_Count__13_ = "31"
Row_Count__14_ = "31"
Row_Count__15_ = "31"
Row_Count__16_ = "31"
Row_Count__17_ = "31"
Row_Count__18_ = "31"
Row_Count__19_ = "31"
Row_Count__20_ = "31"
Row_Count__21_ = "31"
Row_Count__22_ = "31"
Row_Count__23_ = "31"
Row_Count__24_ = "31"
Row_Count__25_ = "31"
Row_Count__26_ = "31"
Row_Count__27_ = "31"
Row_Count__28_ = "31"
Row_Count__29_ = "31"
Row_Count__30_ = "31"
Row_Count__31_ = "31"
Row_Count__32_ = "31"
Row_Count__33_ = "31"
Row_Count__34_ = "31"
Row_Count__35_ = "31"
Row_Count__36_ = "31"

# Process: Transformer le shape de depart en couche...
gp.MakeFeatureLayer_management(LE_grilla_400m_tipo_shp, LE_grilla_400m_tipo, "\"TOT_ESEN\" = 2", "", "Agua_E Agua_E VISIBLE NONE;Alimen_E Alimen_E VISIBLE NONE;Energ_E Energ_E VISIBLE NONE;Salud_E Salud_E VISIBLE NONE;Transp_E Transp_E VISIBLE NONE;Telecom_E Telecom_E VISIBLE NONE;Decis_E Decis_E VISIBLE NONE;Alberg_E Alberg_E VISIBLE NONE;Escomb_E Escomb_E VISIBLE NONE;TOT_ESEN TOT_ESEN VISIBLE NONE;Agua_A Agua_A HIDDEN NONE;Alimen_A Alimen_A HIDDEN NONE;Energ_A Energ_A HIDDEN NONE;Salud_A Salud_A HIDDEN NONE;Transp_A Transp_A HIDDEN NONE;Telecom_A Telecom_A HIDDEN NONE;Decis_A Decis_A HIDDEN NONE;Alberg_A Alberg_A HIDDEN NONE;Escomb_A Escomb_A HIDDEN NONE;Tot_Apoyo Tot_Apoyo HIDDEN NONE;Agua_EA Agua_EA HIDDEN NONE;Alim_EA Alim_EA HIDDEN NONE;Energ_EA Energ_EA HIDDEN NONE;Salud_EA Salud_EA HIDDEN NONE;Transp_EA Transp_EA HIDDEN NONE;Telecom_EA Telecom_EA HIDDEN NONE;Decis_EA Decis_EA HIDDEN NONE;Alberg_EA Alberg_EA HIDDEN NONE;Escomb_EA Escomb_EA HIDDEN NONE;TOT_ES_APO TOT_ES_APO HIDDEN NONE;id id HIDDEN NONE")

# Process: aguaE = 1 and energiaE =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Agua_E\" =1 AND \"Energ_E\" =1")

# Process: export selection (2)...
gp.Select_analysis(Agua_con_energia, LE_aguaE_con_energiaE_shp, "")

# Process: aguaE = 1 and transporteE =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Agua_E\" =1 AND \"Transp_E\" =1")

# Process: export selection (4)...
gp.Select_analysis(Agua_con_transporte, LE_aguaE_con_transporteE_shp, "")

# Process: aguaE = 1 and DecismE =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Agua_E\" =1 AND \"Decis_E\" =1")

# Process: export selection (6)...
gp.Select_analysis(Agua_con_decision, LE_aguaE_con_decisionE_shp, "")

# Process: aguaE = 1 and EscombrE =1 (2)...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Agua_E\" =1 AND \"Escomb_E\" =1")

# Process: export selection (8)...
gp.Select_analysis(Agua_con_escombreras, LE_aguaE_con_escombrerasE_shp, "")

# Process: aguaE = 1 and alimentosE =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Agua_E\" =1 AND \"Alimen_E\" =1")

# Process: export selection...
gp.Select_analysis(Agua_con_alimentos, LE_aguaE_con_alimentosE_shp, "")

# Process: aguaE = 1 and SaludE =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Agua_E\" =1 AND \"Salud_E\" =1")

# Process: export selection (3)...
gp.Select_analysis(Agua_con_Salud, LE_aguaE_con_saludE_shp, "")

# Process: aguaE = 1 and telecomE =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Agua_E\" =1 AND \"Telecom_E\" =1")

# Process: export selection (5)...
gp.Select_analysis(Agua_con_telecom, LE_aguaE_con_telecomE_shp, "")

# Process: aguaE = 1 and AlbergE =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Agua_E\" =1 AND \"Alberg_E\" =1")

# Process: export selection (7)...
gp.Select_analysis(Agua_con_albergue, LE_aguaE_con_albergueE_shp, "")

# Process: AlimentE = 1 and energiaE =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Alimen_E\" =1 AND \"Energ_E\" =1")

# Process: export selection (9)...
gp.Select_analysis(Alimentos_con_energia, LE_alimentosE_con_energiaE_shp, "")

# Process: AlimentE = 1 and saludE =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Alimen_E\" =1 AND \"Salud_E\" =1")

# Process: export selection (10)...
gp.Select_analysis(Alimentos_con_salud, LE_alimentosE_con_saludE_shp, "")

# Process: AlimentE = 1 and transporteE =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Alimen_E\" =1 AND \"Transp_E\" =1")

# Process: export selection (11)...
gp.Select_analysis(Alimentos_con_transporte, LE_alimentosE_con_transporteE_shp, "")

# Process: AlimentE = 1 and telecomE =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Alimen_E\" =1 AND \"Telecom_E\" =1")

# Process: export selection (12)...
gp.Select_analysis(Alimentos_con_telecom, LE_alimentosE_con_telecomE_shp, "")

# Process: AlimentE = 1 and DecisE =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Alimen_E\" =1 AND \"Decis_E\" =1")

# Process: export selection (13)...
gp.Select_analysis(Alimentos_con_decision, LE_alimentosE_con_decisE_shp, "")

# Process: AlimentE = 1 and AlbergE =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Alimen_E\" =1 AND \"Alberg_E\" =1")

# Process: export selection (14)...
gp.Select_analysis(Alimentos_con_albergue, LE_alimentosE_con_albergE_shp, "")

# Process: AlimentE = 1 and EscombrE =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Alimen_E\" =1 AND \"Escomb_E\" =1")

# Process: export selection (15)...
gp.Select_analysis(Alimentos_con_escombreras, LE_alimentosE_con_escombrerasE_shp, "")

# Process: export selection (16)...
gp.Select_analysis(Agua_con_alimentos, LE_alimentosE_con_aguaE_shp, "")

# Process: export selection (17)...
gp.Select_analysis(Agua_con_telecom, LE_telecomE_con_aguaE_shp, "")

# Process: export selection (18)...
gp.Select_analysis(Agua_con_decision, LE_decisionE_con_aguaE_shp, "")

# Process: export selection (19)...
gp.Select_analysis(Agua_con_energia, LE_energiaE_con_aguaE_shp, "")

# Process: export selection (20)...
gp.Select_analysis(Agua_con_transporte, LE_transporteE_con_aguaE_shp, "")

# Process: export selection (21)...
gp.Select_analysis(Agua_con_escombreras, LE_escombrerasE_con_aguaE_shp, "")

# Process: export selection (22)...
gp.Select_analysis(Agua_con_Salud, LE_saludE_con_aguaE_shp, "")

# Process: export selection (23)...
gp.Select_analysis(Agua_con_albergue, LE_albergueE_con_aguaE_shp, "")

# Process: export selection (24)...
gp.Select_analysis(Alimentos_con_salud, LE_saludE_con_alimentosE_shp, "")

# Process: export selection (25)...
gp.Select_analysis(Alimentos_con_telecom, LE_telecomE_con_alimentosE_shp, "")

# Process: export selection (26)...
gp.Select_analysis(Alimentos_con_albergue, LE_albergueE_con_alimentosE_shp, "")

# Process: export selection (27)...
gp.Select_analysis(Alimentos_con_escombreras, LE_escombrerasE_con_alimentosE_shp, "")

# Process: export selection (28)...
gp.Select_analysis(Alimentos_con_decision, LE_decisionE_con_alimentosE_shp, "")

# Process: export selection (29)...
gp.Select_analysis(Alimentos_con_transporte, LE_transporteE_con_alimentosE_shp, "")

# Process: export selection (30)...
gp.Select_analysis(Alimentos_con_energia, LE_energiaE_con_alimentosE_shp, "")

# Process: "Energ_E" =1 AND "Salud_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Energ_E\" =1 AND \"Salud_E\" =1")

# Process: export...
gp.Select_analysis(Energia_con_salud, LE_energiaE_con_saludE_shp, "")

# Process: "Energ_E" =1 AND "Transp_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Energ_E\" =1 AND \"Transp_E\" =1")

# Process: export (2)...
gp.Select_analysis(Energia_con_transporte, LE_energiaE_con_transporteE_shp, "")

# Process: "Energ_E" =1 AND "Telecom_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Energ_E\" =1 AND \"Telecom_E\" =1")

# Process: export (3)...
gp.Select_analysis(Energia_con_telecom, LE_energiaE_con_telecomE_shp, "")

# Process: "Energ_E" =1 AND "Decis_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Energ_E\" =1 AND \"Decis_E\" =1")

# Process: export (4)...
gp.Select_analysis(Energia_con_decision, LE_energiaE_con_decisionE_shp, "")

# Process: export (5)...
gp.Select_analysis(Energia_con_decision, LE_decisionsE_con_energiaE_shp, "")

# Process: export (6)...
gp.Select_analysis(Energia_con_telecom, LE_telecomE_con_energiaE_shp, "")

# Process: export (7)...
gp.Select_analysis(Energia_con_salud, LE_saludE_con_energiaE_shp, "")

# Process: export (8)...
gp.Select_analysis(Energia_con_transporte, LE_transporteE_con_energiaE_shp, "")

# Process: "Energ_E" =1 AND "Alberg_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Energ_E\" =1 AND \"Alberg_E\" =1")

# Process: export (9)...
gp.Select_analysis(Energia_con_albergue, LE_energiaE_con_albergueE_shp, "")

# Process: export (10)...
gp.Select_analysis(Energia_con_albergue, LE_albergueE_con_energiaE_shp, "")

# Process: "Energ_E" =1 AND "Escomb_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Energ_E\" =1 AND \"Escomb_E\" =1")

# Process: export (11)...
gp.Select_analysis(Energia_con_escombreras, LE_energiaE_con_escombrerasE_shp, "")

# Process: export (12)...
gp.Select_analysis(Energia_con_escombreras, LE_escombrerasE_con_energiaE_shp, "")

# Process: "Salud_E" =1 AND "Transp_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Salud_E\" =1 AND \"Transp_E\" =1")

# Process: export (15)...
gp.Select_analysis(Salud_con_transporte, LE_saludE_con_transporteE_shp, "")

# Process: export (16)...
gp.Select_analysis(Salud_con_transporte, LE_transporteE_con_saludE_shp, "")

# Process: "Salud_E" =1 AND "Telecom_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Salud_E\" =1 AND \"Telecom_E\" =1")

# Process: export (13)...
gp.Select_analysis(Salud_con_telecom, LE_saludE_con_telecomE_shp, "")

# Process: export (14)...
gp.Select_analysis(Salud_con_telecom, LE_telecomE_con_saludE_shp, "")

# Process: "Salud_E" =1 AND "Decis_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Salud_E\" =1 AND \"Decis_E\" =1")

# Process: export (17)...
gp.Select_analysis(Salud_con_decision, LE_saludE_con_decisionE_shp, "")

# Process: export (18)...
gp.Select_analysis(Salud_con_decision, LE_decisionE_con_saludE_shp, "")

# Process: "Salud_E" =1 AND "Alberg_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Salud_E\" =1 AND \"Alberg_E\" =1")

# Process: export (19)...
gp.Select_analysis(Salud_con_albergue, LE_saludE_con_albergueE_shp, "")

# Process: export (20)...
gp.Select_analysis(Salud_con_albergue, LE_albergueE_con_saludE_shp, "")

# Process: "Salud_E" =1 AND "Escomb_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Salud_E\" =1 AND \"Escomb_E\" =1")

# Process: export (21)...
gp.Select_analysis(Salud_con_escombreras, LE_saludE_con_escombrerasE_shp, "")

# Process: export (22)...
gp.Select_analysis(Salud_con_escombreras, LE_escombrerasE_con_saludE_shp, "")

# Process: "Transp_E" =1 AND "Telecom_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Transp_E\" =1 AND \"Telecom_E\" =1")

# Process: export (25)...
gp.Select_analysis(Transporte_con_telecom, LE_transporteE_con_telecomE_shp, "")

# Process: export (26)...
gp.Select_analysis(Transporte_con_telecom, LE_telecomE_con_transporteE_shp, "")

# Process: "Transp_E" =1 AND "Decis_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Transp_E\" =1 AND \"Decis_E\" =1")

# Process: export (23)...
gp.Select_analysis(Transporte_con_decision, LE_transporteE_con_decisionE_shp, "")

# Process: export (24)...
gp.Select_analysis(Transporte_con_decision, LE_decisionE_con_transporteE_shp, "")

# Process: "Transp_E" =1 AND "Alberg_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Transp_E\" =1 AND \"Alberg_E\" =1")

# Process: export (27)...
gp.Select_analysis(Transporte_con_albergue, LE_transporteE_con_albergueE_shp, "")

# Process: export (28)...
gp.Select_analysis(Transporte_con_albergue, LE_albergueE_con_transporteE_shp, "")

# Process: "Transp_E" =1 AND "Escomb_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Transp_E\" =1 AND \"Escomb_E\" =1")

# Process: export (29)...
gp.Select_analysis(Transporte_con_escombreras, LE_transporteE_con_escombrerasE_shp, "")

# Process: export (30)...
gp.Select_analysis(Transporte_con_escombreras, LE_escombrerasE_con_transporteE_shp, "")

# Process: "Telecom_E" =1 AND "Decis_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Telecom_E\" =1 AND \"Decis_E\" =1")

# Process: Select...
gp.Select_analysis(Telecom_con_decision, LE_telecomE_con_decisionE_shp, "")

# Process: Select (2)...
gp.Select_analysis(Telecom_con_decision, LE_decisionE_con_telecomE_shp, "")

# Process: "Telecom_E" =1 AND "Alberg_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Telecom_E\" =1 AND \"Alberg_E\" =1")

# Process: Select (3)...
gp.Select_analysis(Telecom_con_albergue, LE_telecomE_con_albergueE_shp, "")

# Process: Select (4)...
gp.Select_analysis(Telecom_con_albergue, LE_albergueE_con_telecomE_shp, "")

# Process: "Telecom_E" =1 AND "Escomb_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Telecom_E\" =1 AND \"Escomb_E\" =1")

# Process: Select (5)...
gp.Select_analysis(Telecom_con_escombreras, LE_telecomE_con_escombrerasE_shp, "")

# Process: Select (6)...
gp.Select_analysis(Telecom_con_escombreras, LE_escombrerasE_con_telecomE_shp, "")

# Process: "Decis_E" =1 AND "Alberg_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Decis_E\" =1 AND \"Alberg_E\" =1")

# Process: Select (7)...
gp.Select_analysis(Decision_con_albergue, LE_decisionE_con_albergueE_shp, "")

# Process: Select (8)...
gp.Select_analysis(Decision_con_albergue, LE_albergueE_con_decisionE_shp, "")

# Process: "Decis_E" =1 AND "Escomb_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Decis_E\" =1 AND \"Escomb_E\" =1")

# Process: Select (9)...
gp.Select_analysis(Decision_con_escombreras, LE_decisionE_con_escombrerasE_shp, "")

# Process: Select (10)...
gp.Select_analysis(Decision_con_escombreras, LE_escombrerasE_con_decisionE_shp, "")

# Process: "Alberg_E" =1 AND "Escomb_E" =1...
gp.SelectLayerByAttribute_management(LE_grilla_400m_tipo, "NEW_SELECTION", "\"Alberg_E\" =1 AND \"Escomb_E\" =1")

# Process: Select (11)...
gp.Select_analysis(Albergue_con_escombreras, LE_albergueE_con_escombrerasE_shp, "")

# Process: Select (12)...
gp.Select_analysis(Albergue_con_escombreras, LE_escombrerasE_con_albergueE_shp, "")

# Process: Compter mailles communes agua y energia...
gp.GetCount_management(Agua_con_energia)

# Process: Compter mailles communes agua y decision...
gp.GetCount_management(Agua_con_decision)

# Process: Compter mailles communes agua y alimentos...
gp.GetCount_management(Agua_con_alimentos)

# Process: Compter mailles communes agua y telecom...
gp.GetCount_management(Agua_con_telecom)

# Process: Compter mailles communes alimentos y energia...
gp.GetCount_management(Alimentos_con_energia)

# Process: Compter mailles communes agua y transporte...
gp.GetCount_management(Agua_con_transporte)

# Process: Compter mailles communes agua y escombreras...
gp.GetCount_management(Agua_con_escombreras)

# Process: Compter mailles communes agua y salud...
gp.GetCount_management(Agua_con_Salud)

# Process: Compter mailles communes agua y albergue...
gp.GetCount_management(Agua_con_albergue)

# Process: Compter mailles communes alimentos y salud...
gp.GetCount_management(Alimentos_con_salud)

# Process: Compter mailles communes alimentos y telecom...
gp.GetCount_management(Alimentos_con_telecom)

# Process: Compter mailles communes alimentos y albergue...
gp.GetCount_management(Alimentos_con_albergue)

# Process: Compter mailles communes alimentos y transporte...
gp.GetCount_management(Alimentos_con_transporte)

# Process: Compter mailles communes alimentos y decision...
gp.GetCount_management(Alimentos_con_decision)

# Process: Compter mailles communes alimentos y escombreras...
gp.GetCount_management(Alimentos_con_escombreras)

# Process: Compter mailles communes energia y transporte...
gp.GetCount_management(Energia_con_transporte)

# Process: Compter mailles communes energia y decision...
gp.GetCount_management(Energia_con_decision)

# Process: Compter mailles communes energia y escombreras...
gp.GetCount_management(Energia_con_escombreras)

# Process: Compter mailles communes energia y albergue...
gp.GetCount_management(Energia_con_albergue)

# Process: Compter mailles communes energia y telecom...
gp.GetCount_management(Energia_con_telecom)

# Process: Compter mailles communes energia y salud...
gp.GetCount_management(Energia_con_salud)

# Process: Compter mailles communes salud y decision...
gp.GetCount_management(Salud_con_decision)

# Process: Compter mailles communes salud y transporte...
gp.GetCount_management(Salud_con_transporte)

# Process: Compter mailles communes salud y escombreras...
gp.GetCount_management(Salud_con_escombreras)

# Process: Compter mailles communes salud y telecom...
gp.GetCount_management(Salud_con_telecom)

# Process: Compter mailles communes salud y albergue...
gp.GetCount_management(Salud_con_albergue)

# Process: Compter mailles communes transporte y telecom...
gp.GetCount_management(Transporte_con_telecom)

# Process: Compter mailles communes transporte y albergue...
gp.GetCount_management(Transporte_con_albergue)

# Process: Compter mailles communes transporte y escombreras...
gp.GetCount_management(Transporte_con_escombreras)

# Process: decision...
gp.GetCount_management(Transporte_con_decision)

# Process: Compter mailles communes telecom y albergue...
gp.GetCount_management(Telecom_con_albergue)

# Process: Compter mailles communes decision y albergue...
gp.GetCount_management(Decision_con_albergue)

# Process: Compter mailles communes telecom y escombreras...
gp.GetCount_management(Telecom_con_escombreras)

# Process: Compter mailles communes decision y escombreras...
gp.GetCount_management(Decision_con_escombreras)

# Process: Compter mailles communes albergue y escombreras...
gp.GetCount_management(Albergue_con_escombreras)

# Process: Compter mailles communes telecom y decision...
gp.GetCount_management(Telecom_con_decision)

